/*
 * This file was generated by the Gradle 'init' task.
 */

import java.time.Instant
import java.time.format.DateTimeFormatter

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("pl.pragmatists:JUnitParams:1.1.1")
}

group = "com.amazon.ion"
version = "1.9.6-SNAPSHOT"
description = "com.amazon.ion:ion-java"
// Can't target 6 from 8
// https://stackoverflow.com/questions/48146930/is-it-possible-to-compile-project-on-java-8-for-target-java-6
java.sourceCompatibility = JavaVersion.VERSION_1_6
var timestamp = Instant.now();

fun buildTimestamp() {
    DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")
        .format(timestamp)
}

fun buildYear() {
    DateTimeFormatter.ofPattern("yyyy")
        .format(timestamp)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])

        pom {
            name.set(description)
            description.set("A Java implementation of the Amazon Ion data notation.")
            url.set("A Java implementation of the Amazon Ion data notation.")
            properties.set(mapOf(
                "build.year" to "${buildYear()}",
                "build.time" to "${buildTimestamp()}"
            ))
            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    name.set("Amazon Ion Team")
                    email.set("ion-team@amazon.com")
                    organization.set("Amazon")
                    organizationUrl.set("https://github.com/amzn")
                }
            }
            scm {
                connection.set("scm:git:git@github.com:amzn/ion-java.git")
                developerConnection.set("scm:git:git@github.com:amzn/ion-java.git")
                url.set("git@github.com:amzn/ion-java.git")
            }
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
